# Generated by Django 4.1 on 2022-08-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wobot_app', '0004_delete_file_student_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.AddField(
            model_name='student',
            name='rdocs',
            field=models.FileField(blank=True, upload_to='rdocs'),
        ),
    ]
