# Generated by Django 4.1 on 2022-08-23 06:47

from django.db import migrations, models
import wobot_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wobot_app', '0007_alter_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to='files', validators=[wobot_app.models.file_size]),
        ),
    ]
